version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: grantdb
    user: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: go-app
#    environment:
#      - DB_HOST=grantdb
#      - DB_PASSWORD=${DB_PASSWORD}
#      - JWT_SECRET=${JWT_SECRET}
#    depends_on:
#      - postgis
#    networks:
#      - app-network
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./configs:/app/configs
#      - ./.env:/app/.env
#    command: [ "./main", "-c", "./configs/config.yml"]
#  weather_app:
#    build:
#      context: .
#      dockerfile: Dockerfile2
#    container_name: go-weather-app
#    environment:
#      - DB_HOST=grantdb
#      - DB_PASSWORD=${DB_PASSWORD}
#      - JWT_SECRET=${JWT_SECRET}
#    depends_on:
#      - postgis
#      - app
#    networks:
#      - app-network
#    ports:
#      - "8081:8081"
#    volumes:
#      - ./configs:/app/configs
#      - ./.env:/app/.env
#    command: [ "./main", "-c", "./configs/config.yml"]

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge