services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgres-grant
    user: postgres
    environment:
      POSTGRES_USER: trailblazer_user1
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trailblazerDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: