server:
  port: "8080"

db:
  dir: "./landmarks/landmark.json"
  port: "5432"
  username: "trailblazer_user1"
  dbname: "trailblazerDB"
  sslmode: "disable"


parser:
  is_production: false
  base_url: "https://www.kp.ru/russia/krym/dostoprimechatelnosti/"
weather:
  lang: "RU"
  url: "https://api.openweathermap.org"
